/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BatchActionsInterface extends utils.Interface {
  functions: {
    "approveAndTransfer20Batch(address[],uint256[],address[])": FunctionFragment;
    "executeBatch(address[],uint256[],bytes[],uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "approveAndTransfer20Batch" | "executeBatch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveAndTransfer20Batch",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAndTransfer20Batch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BatchActions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BatchActionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveAndTransfer20Batch(
      tokenAddress: PromiseOrValue<string>[],
      amount: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeBatch(
      to: PromiseOrValue<string>[],
      value: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>[],
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  approveAndTransfer20Batch(
    tokenAddress: PromiseOrValue<string>[],
    amount: PromiseOrValue<BigNumberish>[],
    to: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeBatch(
    to: PromiseOrValue<string>[],
    value: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>[],
    operation: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveAndTransfer20Batch(
      tokenAddress: PromiseOrValue<string>[],
      amount: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    executeBatch(
      to: PromiseOrValue<string>[],
      value: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>[],
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveAndTransfer20Batch(
      tokenAddress: PromiseOrValue<string>[],
      amount: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeBatch(
      to: PromiseOrValue<string>[],
      value: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>[],
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveAndTransfer20Batch(
      tokenAddress: PromiseOrValue<string>[],
      amount: PromiseOrValue<BigNumberish>[],
      to: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeBatch(
      to: PromiseOrValue<string>[],
      value: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>[],
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
